name: "Auto approve"

on:
  - pull_request_target

jobs:
  auto-approve:
    runs-on: "ubuntu-24.04"

    if: ${{ github.actor == 'dependabot[bot]' }}

    permissions:
      pull-requests: write

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          lfs: false
          persist-credentials: false

      - name: "Approve patch and minor updates"
        run: |
          gh pr checkout "$PR_URL" # sets the upstream metadata for `gh pr status`
          if [ "$(gh pr status --json reviewDecision -q .currentBranch.reviewDecision)" != "APPROVED" ];
          then gh pr review --approve "$PR_URL"
          else echo "PR already approved, skipping additional approvals to minimize emails/notification noise.";
          fi
        env:
          PR_URL: "${{ github.event.pull_request.html_url }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
